[workspace.package]
version = "0.1.0"
edition = "2021"
# TODO(template) update for your repository
repository = "https://github.com/NethermindEth/rust-template"
license = "Apache-2.0" # TODO(template) update license if needed

# TODO(template) update for the crate name
[workspace]
members = [
    "interfaces",
    "contracts/contract_a",
    "contracts/contract_b",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = { version = "22.0.1", default-features = false }
interfaces = { path = "./interfaces" }
contract_a = { path = "./contracts/contract_a" }

[workspace.dev-dependencies]
soroban-sdk = { version = "22.0.1", features = ["testutils"] }

[workspace.lints.rust]
#missing_docs = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
arithmetic_side_effects = "deny"
cast_lossless = "deny"
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_sign_loss = "deny"
needless_return = "deny"
panicking_overflow_checks = "deny"
unwrap_used = "deny"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true